### ISSUE TITLE
Activity-specific colors varies throughout app

### ISSUE THREAD

**Issue by joakimljunglin** [joakimljunglin/DVA232-ProjectGroup4#19]
As I finished the result page and made it retrieve the activity-specific colors from the resources in colors.xml, I realized the use of these colors aren't consistent throughout the app. I found this issue on these two areas:

1. The reading activity has different colors on the home page and when listing its tests when clicked (the color on the homepage is in line with the color resource).
2. The colors for the listening and vocabulary activities are mixed up.

Apart from these areas it seems consistent. I'm not sure where or how these colors are set in these areas. Would it somehow be possible to make the colors consistent?

**Comment by ghost** [comment]
Fair point. @ediuva knows that part of the app better than me, so I will remove my assignment.

**Comment by ediuva** [comment]
Ok I will see about it

**Comment by ediuva** [comment]
I created a pull request with the result page file modified so the colors are the same as the other pages.
@joakimljunglin you said that the colors for the listening and vocabulary activities are mixed up but I think that this issue has already been solved because I didn't see anything like that in the app.

**Comment by joakimljunglin** [comment]
@ediuva I've reviewed your pull request and will approve it. The colors are now consistent and correct. The mix up was fixed in a previous merge that I had missed, so that is also resolved as well.

I will approve and merge your pull request. Thank you!
